import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import AppProvider from "./components/provider/app-provider";
import { luciole, lexend } from "./styles/styles";
import Header from "./components/header/header";

export const metadata: Metadata = {
   title: "Ben's portfolio",
   description: "Generated by his own hands",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="fr"
         className={`${luciole.variable} ${lexend.variable} h-full antialiased`}
         suppressHydrationWarning
      >
         {/* <body className="min-h-full flex flex-col"> */}
         <body className="min-h-full ">
            <Script id="thematic" strategy="beforeInteractive">
               {`
            try {
              var themeInfo = localStorage.getItem('theme');
              if (themeInfo) document.documentElement.setAttribute('data-theme', themeInfo);
              var localeInfo = localStorage.getItem('locale');
              if (localeInfo) document.documentElement.lang = localeInfo;
            } catch (e) {
             console.log(e)}   
          `}
            </Script>
            <AppProvider>
               <Header />
               {children}
            </AppProvider>
         </body>
      </html>
   );
}
